### ISSUE TITLE
Creation of a table with a foreign key fails

### ISSUE THREAD

**Issue by gio-shara-code** [tablelandnetwork/js-tableland#32]
## Expected Behavior
Creation of tables with relations (with primary key and foreign key)

## Actual Behavior
When I try to create a table with a foreign key property, it falis:
`(node:2592) UnhandledPromiseRejectionWarning: Error: processing table registration: processing register table: exec CREATE statement: ERROR: relation "tablename" does not exist (SQLSTATE 42P01)`

## Specifications

- @tableland/sdk: ^0.0.1

## My Code

```
export const table1TableScript = () =>
	'CREATE TABLE Table1(id int,  primary key (id));';

export const table2TableScript = () =>
	'CREATE TABLE Table2(id int, table1_id int REFERENCES Table1(id),  primary key (id));'; //Also tried instead of 'Table1' -> 'table1_id'

```

First I create 'Table1' and afterwards run the 'table2TableScript' script which fails...

Appreciate your help.

**Comment by joewagner** [comment]
@gio-shara-code Sorry for the slow response, I'm on holiday this week.  I think I see the issue with the example you posted, but I won't be able to dig in until next week.
 - When you create a table in Tableland the Validator is going to automatically append a unique id to the end of the table name.  This ensures that all tables have a unique name, also worth note, the id is the tokenId of the table in the smart contract.  Your second statement has the line `REFERENCES Table1(id)`, `Table1` doesn't exist because the table Id isn't appended.  The docs have an example in the [basic usage](https://docs.tableland.xyz/building/javascript-sdk#basic-usage) section of the SDK page.
 -  This isn't actually an issue(more of a nit), and you may already know this, but something to keep in mind is that SQL table names are not case sensitive unless you quote them, so `CREATE TABLE Table1(id int,  primary key (id));` is going to result in an all lowercase table name.  This doesn't actually matter because your second statement's `REFERENCES Table1(id)` is also not case sensitive.  I only mention it, because I've seen it result in bugs if a future dev doesn't realize that the case is being ignored.

For more complete usage patterns you can look into our [example apps](https://github.com/tablelandnetwork/example-apps).  Also, most of the Tableland community hangs out in [Discord](https://discord.com/invite/A7JpNjpk3K), feel free to ask for help there too.

**Comment by joewagner** [comment]
Closing from lack of response
