### ISSUE TITLE
[JST-19] Readme Q/A cleanup of usage

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/js-tableland#457]
I'm looking to upgrade one of the example repos with the latest SDK. The usage example is confusing on a couple parts. 

1. Am i required to install ethers to just read data? Maybe split the usage into two examples, one read one write? Include ethers install step. 
2. If I'm just reading, do i need a provider? do i need a signer? does the database constructor need a signer? Can i self-assign the read network vs pulling it from the wallet (making it a more common pattern i believe). Splitting out a read only usage example might be all that's needed. 

<sub>From [SyncLinear.com](https://synclinear.com) | [JST-19](https://linear.app/tableland/issue/JST-19/readme-qa-cleanup-of-usage)</sub>

**Comment by sanderpick** [comment]
> 1. Am i required to install ethers to just read data? Maybe split the usage into two examples, one read one write? Include ethers install step. 

I don't believe so. You shouldn't need a provider for simple reads. The SDK ships with ethers though. 

IIRC, you can use an empty constructor for read-only. @carsonfarmer would know for sure.

**Comment by andrewxhill** [comment]
okay, i get react errors when i use the ethers import step in the current repo (w/o installing ethers on my own)

**Comment by joewagner** [comment]
> I'm looking to upgrade one of the example repos with the latest SDK. The usage example is confusing on a couple parts.

I agree the README example is a bit confusing, and out of date.  We should probably take some of the examples from the docs, or just link to the docs: https://docs.tableland.xyz/sdk/core/
 
> 1. Am i required to install ethers to just read data? Maybe split the usage into two examples, one read one write? Include ethers install step.

You should not ever *need* ethers if you're app is running in the browser.  This is because the browser wallet will be where the signer+provider comes from.  Note: your app might need ethers.js for some other reason, but not because of the SDK.

> 2. If I'm just reading, do i need a provider? do i need a signer? does the database constructor need a signer?

For reads all you need is 
```
import { Database } from "@tableland/sdk";

const tableName = "healthbot_80001_1"; // Our pre-defined health check table

const db = new Database();

const { results } = await db.prepare(`SELECT * FROM ${tableName};`).all();
console.log(results);
```

The docs have [good explanations and an example.](https://docs.tableland.xyz/sdk/core/#reads) 

> Can i self-assign the read network vs pulling it from the wallet (making it a more common pattern i believe). Splitting out a read only usage example might be all that's needed.

This is a little more nuanced.  If you are just doing reads, then the network your wallet is connected to doesn't make any difference.
If you are doing creates or writes then the Wallet must be the connected to the chain you want to write or create on.  If this is in the context of a browser, the user will have the final say on what network they choose to connect their wallet to, unless the app developer finds a clever way to proxy contract transactions on behalf of the user (aka do a relay where they pay for the transaction gas, and own the table)

**Comment by joewagner** [comment]
> okay, i get react errors when i use the ethers import step in the current repo readme (w/o installing ethers on my own)

For a react app you might not need ethers.  What are the errors?

**Comment by andrewxhill** [comment]
got it, the example has 

```
import { providers } from "ethers";
```

so react will complain that ethers doesn't exist if you don't install it manually

**Comment by joewagner** [comment]
That makes sense.  I can take a stab at updating the README, unless we want to remove the examples and link to the docs?

**Comment by dtbuchholz** [comment]
fwiw, i didn't have issues with react complaining about ethers when _not_ installing ethers manually, e.g., if doing the setup outlined here: https://docs.tableland.xyz/quickstarts/reactjs
