### ISSUE TITLE
Multiple INSERT ops in one tx?

### ISSUE THREAD

**Issue by wbt** [tablelandnetwork/js-tableland#87]
Is it possible to have multiple INSERT operations (e.g. writing data to two tables) in the same EVN transaction? 
I seem to remember reading that it's not possible to have two CREATE TABLE operations in one transaction, though the docs search feature seems broken and I can't find exactly where, and the [limits section](https://docs.tableland.xyz/limits-and-deployed-contracts) doesn't say anything about even that restriction.

I am trying to run a smart contract with two functions (that matter for this discussion): one that does an INSERT query, and another that does a different INSERT query on a conceptually related table and then calls the first one for a second INSERT.  Calling just the first function by itself works fine, with results visible on a subsequent SELECT. On calling the second, I can see the first INSERT take effect with the INSERTed data returned in a subsequent SELECT.  However, the second INSERT seems to silently fail when it's called from the second function.  The first function still proceeds to emit an event indicating successful update, in which the parameters appear correct, but the data isn't reflected in any subsequent read operation.  

The only thing I can think of at the moment as a possible reason is an undocumented restriction against writing to more than one table in one query.  Such a restriction (especially undocumented!) would be pretty severe limit on the use of the relational data table model.  

It's also a bit concerning that the Tableland INSERT call succeeds without revert() even when the call is failing and the data is not getting added - is there any good way to detect that in the EVM environment?

Under "walkthroughs" on the left there's one for the Javascript SDK but not for EVN / Solidity. At the bottom (e.g. of [this](https://docs.tableland.xyz/javascript-sdk) page there's a link to "Hop into Discord" which is a completely empty server, visible only after completing Discord's full sign-up process if needed:
![image](https://user-images.githubusercontent.com/563406/181623067-a7a5c32e-05ee-42d1-8198-247bb97611f1.png)
It's the same result when using the [Discord link](https://discord.gg/dc8EBEhGbg) on the [Community page](https://docs.tableland.xyz/community).

The website repo, visited in the hopes that GitHub search might work better than the on-site search, [reports](https://github.com/tablelandnetwork/docs) that it's archived with reference to a different Discord link, which renders like this:
![image](https://user-images.githubusercontent.com/563406/181623251-44f00703-84ba-4c77-a624-dc93eb4b2dd2.png)

Therefore I'm posting here, but figured I'd include those notices to provide a better idea of what Tableland's new user experience is currently like.

**Comment by eightysteele** [comment]
Hey @wbt, what's your full Discord username (with the `#` part)?

**Comment by joewagner** [comment]
@wbt Sorry you are having trouble getting into Discord.  
It doesn't seem like this issue has anything to do with the Javascript SDK, is that correct?

**Comment by joewagner** [comment]
@wbt I'm closing for lack of response, and because I don't think this is an issue with the Javascript SDK.  However you are asking a really good question here in regard to the multiple events per transaction.  Would you be willing to ask it on one of the stackexchange.com sites, e.g. stackoverflow.com?  If so please tag the question with `tableland`, you would be the first question!  This would be helpful both because your question might help others, but also these kinds of questions can clutter github issues if it becomes a regular thing.

**Comment by wbt** [comment]
This issue is about whether you can do multiple INSERT operations in one transaction, secondarily pointing out a pretty bad new user experience trying to ask questions in Discord.  I sent a friend request on Discord to @eightysteele shortly after the request above, but I don't think it should matter what my handle is because (a) that's irrelevant to whether multiple INSERT operations can happen in one transaction and (b) the same issue is observed with a newly created account.  

With such a small user base, and barriers keeping that user base small, general Q&A sites are unlikely to be much help, especially when such a high percentage of such questions have turned out to be actual issues in Tableland and in each case including this one, at least formal documentation should be updated if nothing else.

In the lack of any substantive answer to the question, combined with the observations that led to it, I'll assume Tableland simply does not support multiple INSERT operations in a single transaction in addition to not supporting on-chain/EVM reads of data, and rip it out.  It's nowhere near ready and there seems to be way more focus on inflating the value of Rigs than actually building functional software consistent with the stated vision.

**Comment by joewagner** [comment]
@wbt your question is definitely a good one, we are just finished implementing your feature.  However the question is not related to this repository.  That's why I closed this.
I have an alert setup for questions that are tagged with `tableland` on stackexchange.  No one has asked a question yet, so if you want to ask questions there i'll do my best to answer them.
RE Discord: we have had issues with Discord, sorry again you not able to get in.

**Comment by eightysteele** [comment]
Hey @wbt, signal boosting my earlier question:

> Hey @wbt, what's your full Discord username (with the # part)?

We have DMs turned off and I haven't seen any friend requests from you yet on Discord.

If you can give me your full username, I'll add you as a friend directly and we'll get you back on the server ASAP. Sorry for the hassle.

eighty

**Comment by wbt** [comment]
Not posting that currently on public GitHub, but it's not really relevant to the question and doesn't help anybody else (which was the original goal of noting that it's currently broken).  This wasn't in the evm-tableland repo as there's no official documentation for that and this seemed to be the closest place to an answer, but it probably could be migrated to the other repo for closer topical alignment, in the bottom part of the right column (visible to maintainers): 
![image](https://user-images.githubusercontent.com/563406/183126747-cb1a6713-e129-418d-a976-e4e955afe440.png)

**Comment by wbt** [comment]
Are there any plans to transfer this issue to the SDK repo and reopen there, or is it better to just leave the answer a secret?

**Comment by joewagner** [comment]
@wbt no plans to move this, because it is not an issue.  Please ask questions on Discord or stackoverflow.  Your comments are getting a bit negative, please keep things civil.

**Comment by wbt** [comment]
On StackOverflow, answers are supposed to cite authoritative sources like a link to documentation - but there isn't any answer to this in the official documentation, and an action from a GitHub Issue could be to add it...that is not an outcome from a SO question. 
Discord is not accessible to newcomers and there's no desire to change that, so the advice to go there isn't generally applicable either.

**Comment by sanderpick** [comment]
> On StackOverflow, answers are supposed to cite authoritative sources like a link to documentation - but there isn't any answer to this in the official documentation, and an action from a GitHub Issue could be to add it...that is not an outcome from a SO question. Discord is not accessible to newcomers and there's no desire to change that, so the advice to go there isn't generally applicable either.

@wbt sorry you're hitting walls with our docs and discord! we (mostly @dtbuchholz) have been racing to add every bit of relevant info to the docs as we get feedback.

@dtbuchholz if it's not there, can we add a mention in the docs that we now support touching multiple tables in a single transaction? we should also mention that SQL statement validation is not handled in the EVM... and stress the importance of doing dry runs.

@wbt we are working to bring our custom SQL parser into the browser via WASM. One of the benefits of doing that it so the SDK can do SQL statement validation w/o having to talk with a validator.

**Comment by dtbuchholz** [comment]
@sanderpick Good callout. Added the first half of that and will include info on dry runs & testing in a new docs page.

@wbt Appreciate you providing this feedback and working with our codebase / protocol! I was super impressed by your HackFS project...[SignReliably](https://github.com/wbt/signreliably) was easily one of the coolest and most innovative hacks that we saw (it was really tough to make a decision).

Anyways, I've added a couple of docs that'll hopefully make _some_ things clearer. If there are other docs you're looking for, I'm all ears (also noted down some of your other comments). We need better docs and value the input!

- Added some clarity on smart contract limits and EVM-dependent "lags" due to tx / block finalization dependency, which includes a brief on the point below: https://docs.tableland.xyz/limits-and-deployed-contracts
- Added a dedicated page on multi-tx support from our protocol team, which was originally was going to be a blog, but I think you've convinced me that it's best served a dev resource within the docs: https://docs.tableland.xyz/docs-admin-db/affecting-tableland-state
